version: "3"
services:
  front:
      build: ./frontend
      container_name: node
      volumes:
        - ./frontend:/front
      working_dir: /front
      ports:
        - 3000:3000
      tty: true
      stdin_open: true
      environment:
        - CHOKIDAR_USEPOLLING=true
  # バックエンド
  app:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: app
    volumes:
      - ./backend/app:/usr/src/app
    command: flask run --host=0.0.0.0
  # データベース
  database:
    image: postgres:9.3
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
      - ./sql/postgres/initdb.d:/docker-entrypoint-initdb.d
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
volumes:
  node_modules_volume: